version: '3.8'
services:
  link-back-app:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=80
      - CHOKIDAR_USEPOLLING=true

networks:
  default:
    name: link-back-app_connect_mysql_default
    external: true